services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"