services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address=":9001"
  rabbitmq:
    image: rabbitmq:3.13-management # Use the version with the web UI
    env_file:
      - .env
    ports:
      - "5672:5672"   # Port for your Spring Boot app to connect
      - "15672:15672"  # Port for the web management UI