spring:
  application:
    name: Admin System

  config:
    import: file:application-secrets.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt.pub

server:
  servlet:
    context-path: /api

  error:
    include-message: always

logging:
  file:
    path: ./logs

  level:
    org.springframework.security: TRACE
    lk.gov.mohe.adminsystem: DEBUG

custom:
  jwt:
    private-key: classpath:keys/jwt.key
    public-key: classpath:keys/jwt.pub
    access-token-validity-seconds: 300 # 5 minutes
    refresh-token-validity-seconds: 2592000 # 30 days
    max-tokens-per-user: 5

  security:
    refresh-token-cookie:
      name: refresh_token
      paths: /api/refresh-token, /api/logout, /api/logout-all
      http-only: true
      secure: true
      same-site: Strict

  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: Content-Type, Authorization, X-XSRF-TOKEN

  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}