spring:
  application:
    name: Admin System

  config:
    import: file:application-secrets.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/jwt.pub

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1024MB

server:
  servlet:
    context-path: /api

  error:
    include-message: always

logging:
  file:
    path: ./logs

  level:
    org.springframework.security: TRACE
    lk.gov.mohe.adminsystem: DEBUG

custom:
  jwt:
    private-key: classpath:keys/jwt.key
    public-key: classpath:keys/jwt.pub
    access-token-validity-seconds: 300 # 5 minutes
    refresh-token-validity-seconds: 2592000 # 30 days
    max-tokens-per-user: 5

  security:
    refresh-token-cookie:
      name: refresh_token
      paths: /api/refresh-token, /api/logout, /api/logout-all
      http-only: true
      secure: true
      same-site: Strict

  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET, POST, PUT, PATCH, DELETE
    allowed-headers: Content-Type, Authorization, X-XSRF-TOKEN

  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}

  attachments:
    accepted-mime-types: >
      text/plain,
      image/png,
      image/jpeg,
      application/pdf,
      application/msword,
      application/vnd.openxmlformats-officedocument.wordprocessingml.document
