services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - "5432:5432"